name: Print vars and secrets

inputs:
  environment:
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Print aja
      environment: Staging
      shell: bash
      env:
        test1: ${{ secrets.ADMIN_PASSWORD }}
        test2: ${{ vars.TOKEN}}
      run: |
        echo "${{ env.test1 }}"
        echo ini adalah $test2