name: Print vars and secrets

inputs:
  test1:
    type: string
    required: true
  test2:
    required: true

runs:
  using: composite
  steps:
    - name: Print aja
      shell: bash
      run: |
        echo "${{ inputs.test1 }}"
        echo ini adalah ${{ inputs.test2 }}