name: Deploy website
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      is_rfc:
        default: false
        type: boolean
      config_test_ready:
        default: false
        type: boolean
      service_name:
        required: true
        type: string
      service_path:
        default: .
        type: string
      program_lang:
        required: true
        type: string
      environment:
        type: string
        description: environment to deploy to
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: gogo
      uses: ivanhermawan19/gh-events/action/printvar@main
      with:
        environment: ${{ inputs.environment }}
